### ISSUE TITLE
make this support baileys multidevice

### ISSUE THREAD

**Issue by Mengrio** [souravkl11/Raganork#23]
If it was made to support baileys multidevice, it would be great

**Comment by souravkl11** [comment]
> If it was made to support baileys multidevice, it would be great

Hey! @Mengrio, I'm currently working on it and the support will be added only after the stable release of multi-device!

**Comment by souravkl11** [comment]
> If it was made to support baileys multidevice, it would be great

Hey Mengrio, Raganork now supports multi device version. Link in readme!
